id: P004498
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:27:15.982360
source_metadata:
  id: bdr:W2CZ9107
  title: ཐུན་མོང་ཞེས་པ་ལྕགས་ཕོ་ཁྱི་ལོའི་ལོ་ཐོ
  author: ''
  volumes:
    a6d95ecc74dd434d893ccebdcadfb189:
      image_group_id: I1PD97761
      title: ''
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
