id: P004498
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ9107
  title: ཐུན་མོང་ཞེས་པ་ལྕགས་ཕོ་ཁྱི་ལོའི་ལོ་ཐོ
  author: ''
  volumes:
    a6d95ecc74dd434d893ccebdcadfb189:
      image_group_id: I1PD97761
      title: ''
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
